### ISSUE TITLE
Tree.query fails in Python interface

### ISSUE THREAD

**Issue by schlegelp** [cavemanloverboy/bosque#5]
Hi! I just tried taking `bosque` for a spin in Python and ran into an issue:

```python
>>> from bosque_py import Tree
>>> import numpy as np
>>> DATA = 100_000
>>> QUERY = 1_000_000

>>> data = np.random.uniform(size=(DATA, 3))
>>> query = np.random.uniform(size=(QUERY, 3))

>>> tree = Tree(data)
>>> tree.query(query, 1)
thread '<unnamed>' panicked at /Users/philipps/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_constructors.rs:516:9:
assertion failed: dimension::can_index_slice(&v, &dim, &strides).is_ok()
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
Cell In[2], line 10
      7 query = np.random.uniform(size=(QUERY, 3))
      9 tree = Tree(data)
---> 10 tree.query(query, 1)

PanicException: assertion failed: dimension::can_index_slice(&v, &dim, &strides).is_ok()
```

This is with commit a8f8fca4423223588bada770fa00f1f1e6ae0105 of `bosque`, `rustc 1.73.0`, `maturin 1.3.0` and `numpy 1.26.1`. 

Any ideas?

**Comment by cavemanloverboy** [comment]
I will try to reproduce your environment and error, but it seems rather odd to me. While I do that... what type of machine are you on?

**Comment by cavemanloverboy** [comment]
Using
```
% rustc --version
rustc 1.73.0 (cc66ad468 2023-10-03)
```
as well as 
```
 pip list | grep numpy    
numpy                       1.26.1
```
and
```
% pip list | grep maturin
maturin                     1.3.0
```
on a freshly cloned repository
```
% git log
commit a8f8fca4423223588bada770fa00f1f1e6ae0105 (HEAD -> main, origin/main, origin/HEAD)
Merge: 489aa75 1281fee
Author: cavemanloverboy <93507302+cavemanloverboy@users.noreply.github.com>
Date:   Thu Sep 28 12:58:47 2023 -0700

    Merge pull request #3 from yipihey/patch-1
    
    Update generator.jl
 ```
 
 I ran the following script 
 ```python
from bosque_py import Tree
import numpy as np
DATA = 100_000
QUERY = 1_000_000

data = np.random.uniform(size=(DATA, 3))
query = np.random.uniform(size=(QUERY, 3))

tree = Tree(data)
tree.query(query, 1)

print("all done")
```
on an Apple Macbook with M2 Max and saw
```
% python repro.py        
all done
```

Without a reproducer, I cannot do much for you I am afraid.

**Comment by cavemanloverboy** [comment]
oh, what python version are you on? The current maturin setup requires `>=3.7`

**Comment by schlegelp** [comment]
Oh, strange...This was with Python 3.9 on OSX (Intel X86). 

What Python were you using?

**Comment by cavemanloverboy** [comment]
> Oh, strange...This was with Python 3.9 on OSX (Intel X86).
> 
> What Python were you using?
```
 python --version
Python 3.10.10
```

**Comment by schlegelp** [comment]
I just tested with Python `3.10.10` in a fresh environment and got the same error.

Just in case you spot something, here is the maturin build log:
```bash 
philipps$ maturin build
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /Users/philipps/.pyenv/versions/3.10.10/bin/python3
📡 Using build options features from pyproject.toml
💻 Using `MACOSX_DEPLOYMENT_TARGET=10.7` for x86_64-apple-darwin by default
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
   Compiling pyo3-build-config v0.19.2
   Compiling pyo3-ffi v0.19.2
   Compiling pyo3 v0.19.2
   Compiling numpy v0.19.0
   Compiling bosque-py v0.1.0 (/Users/philipps/Google Drive/Cloudbox/Github/bosque/py)
    Finished dev [unoptimized + debuginfo] target(s) in 10.96s
📦 Built wheel for CPython 3.10 to /Users/philipps/Google Drive/Cloudbox/Github/bosque/target/wheels/bosque_py-0.1.0-cp310-cp310-macosx_10_7_x86_64.whl
```

I'll see if I can try on a ARM Mac at work.

**Comment by cavemanloverboy** [comment]
> I just tested with Python `3.10.10` in a fresh environment and got the same error.
> 
> Just in case you spot something, here is the maturin build log:
> 
> ```shell
> philipps$ maturin build
> warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
> note: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
> note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
> 🔗 Found pyo3 bindings
> 🐍 Found CPython 3.10 at /Users/philipps/.pyenv/versions/3.10.10/bin/python3
> 📡 Using build options features from pyproject.toml
> 💻 Using `MACOSX_DEPLOYMENT_TARGET=10.7` for x86_64-apple-darwin by default
> warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
> note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
> note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
>    Compiling pyo3-build-config v0.19.2
>    Compiling pyo3-ffi v0.19.2
>    Compiling pyo3 v0.19.2
>    Compiling numpy v0.19.0
>    Compiling bosque-py v0.1.0 (/Users/philipps/Google Drive/Cloudbox/Github/bosque/py)
>     Finished dev [unoptimized + debuginfo] target(s) in 10.96s
> 📦 Built wheel for CPython 3.10 to /Users/philipps/Google Drive/Cloudbox/Github/bosque/target/wheels/bosque_py-0.1.0-cp310-cp310-macosx_10_7_x86_64.whl
> ```
> 
> I'll see if I can try on a ARM Mac at work.

i don't think this is it, but either way you should be using `maturin develop --release` to enable optimizations within `bosque`

**Comment by cavemanloverboy** [comment]
> I just tested with Python `3.10.10` in a fresh environment and got the same error.
> 
> Just in case you spot something, here is the maturin build log:
> 
> ```shell
> philipps$ maturin build
> warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
> note: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the worknote: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
> note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
> 🔗 Found pyo3 bindings
> 🐍 Found CPython 3.10 at /Users/philipps/.pyenv/versions/3.10.10/bin/python3
> 📡 Using build options features from pyproject.toml
> 💻 Using `MACOSX_DEPLOYMENT_TARGET=10.7` for x86_64-apple-darwin by default
> warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
> note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
> note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
>    Compiling pyo3-build-config v0.19.2
>    Compiling pyo3-ffi v0.19.2
>    Compiling pyo3 v0.19.2
>    Compiling numpy v0.19.0
>    Compiling bosque-py v0.1.0 (/Users/philipps/Google Drive/Cloudbox/Github/bosque/py)
>     Finished dev [unoptimized + debuginfo] target(s) in 10.96s
> 📦 Built wheel for CPython 3.10 to /Users/philipps/Google Drive/Cloudbox/Github/bosque/target/wheels/bosque_py-0.1.0-cp310-cp310-macosx_10_7_x86_64.whl
> ```
> 
> I'll see if I can try on a ARM Mac at work.

any progress on this?

**Comment by schlegelp** [comment]
Sorry, this totally fell off my radar.

I didn't make any progress, all I can offer is a full traceback in case that's helpful:

```bash 
$ export RUST_BACKTRACE="full"
$ python3 examples/python/comparison.py 
-------------------------- bosque results -------------------------
bosque finished build in 42 millis
thread '<unnamed>' panicked at /Users/philipps/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_constructors.rs:516:9:
assertion failed: dimension::can_index_slice(&v, &dim, &strides).is_ok()
stack backtrace:
   0:        0x100fbbc0b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h65343ad3a85b4e34
   1:        0x100fd92db - core::fmt::write::h11839d3825cb5605
   2:        0x100fb99be - std::io::Write::write_fmt::h3ab12d369399333c
   3:        0x100fbb9e9 - std::sys_common::backtrace::print::h405f7c76ca12eb27
   4:        0x100fbd065 - std::panicking::default_hook::{{closure}}::hed87c355606e1822
   5:        0x100fbcd91 - std::panicking::default_hook::hdf696ec8ea0d65aa
   6:        0x100fbd5d0 - std::panicking::rust_panic_with_hook::h7c5059af1af54377
   7:        0x100fbd4b2 - std::panicking::begin_panic_handler::{{closure}}::hd658b0e1cffe3d4d
   8:        0x100fbc0e9 - std::sys_common::backtrace::__rust_end_short_backtrace::h3d7834d0cea60a50
   9:        0x100fbd21d - _rust_begin_unwind
  10:        0x100fe7d63 - core::panicking::panic_fmt::ha9964785de0afb40
  11:        0x100fe7df7 - core::panicking::panic::h604fa998dd50d7a6
  12:        0x100eb422f - ndarray::impl_constructors::<impl ndarray::ArrayBase<S,D>>::from_vec_dim_stride_unchecked::h151e6a177eaca215
                               at /Users/philipps/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_constructors.rs:516:9
  13:        0x100eb3b9d - ndarray::impl_constructors::<impl ndarray::ArrayBase<S,D>>::from_shape_vec_unchecked::ha11b3dcb477f7d86
                               at /Users/philipps/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ndarray-0.15.6/src/impl_constructors.rs:511:9
  14:        0x100ee96cb - bosque_py::bosque_py::Tree::query::h6eb3309851163b08
                               at /Users/philipps/Google Drive/Cloudbox/Github/bosque/py/src/lib.rs:193:37
  15:        0x100eea464 - bosque_py::bosque_py::_::<impl bosque_py::bosque_py::Tree>::__pymethod_query__::hf5b00214d6e9e405
                               at /Users/philipps/Google Drive/Cloudbox/Github/bosque/py/src/lib.rs:100:5
  16:        0x100eb8766 - pyo3::impl_::trampoline::fastcall_with_keywords::{{closure}}::h31d8400b552b4b80
                               at /Users/philipps/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.2/src/impl_/trampoline.rs:41:29
  17:        0x100eb865b - pyo3::impl_::trampoline::trampoline::{{closure}}::h60f86a636eb3b64e
                               at /Users/philipps/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.2/src/impl_/trampoline.rs:181:54
  18:        0x100eda45e - std::panicking::try::do_call::h0136451737557b53
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  19:        0x100edaf7d - ___rust_try
  20:        0x100eda207 - std::panicking::try::hd3ec4cb30c4c9cec
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  21:        0x100eade24 - std::panic::catch_unwind::h7b7e2d74952fcf55
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  22:        0x100eb8564 - pyo3::impl_::trampoline::trampoline::h8e5a24a6662a98d8
                               at /Users/philipps/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.2/src/impl_/trampoline.rs:181:9
  23:        0x100ee763d - pyo3::impl_::trampoline::fastcall_with_keywords::h32fe5f136e597222
                               at /Users/philipps/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.19.2/src/impl_/trampoline.rs:41:13
  24:        0x100ee9ab4 - bosque_py::bosque_py::_::<impl pyo3::impl_::pyclass::PyMethods<bosque_py::bosque_py::Tree> for pyo3::impl_::pyclass::PyClassImplCollector<bosque_py::bosque_py::Tree>>::py_methods::ITEMS::trampoline::he4ee22f393b619a1
                               at /Users/philipps/Google Drive/Cloudbox/Github/bosque/py/src/lib.rs:100:5
  25:        0x1007cd3ca - _method_vectorcall_FASTCALL_KEYWORDS
  26:        0x1008b6afe - _call_function
  27:        0x1008b33dc - __PyEval_EvalFrameDefault
  28:        0x1008ac282 - __PyEval_Vector
  29:        0x1008ac1d8 - _PyEval_EvalCode
  30:        0x10090042e - __PyRun_SimpleFileObject
  31:        0x1008ffe0b - __PyRun_AnyFileObject
  32:        0x100920f7a - _Py_RunMain
  33:        0x1009216f3 - _pymain_main
  34:        0x10092179b - _Py_BytesMain
Traceback (most recent call last):
  File "/Users/philipps/Google Drive/Cloudbox/Github/bosque/examples/python/comparison.py", line 28, in <module>
    r, ids = tree.query(query, K)
pyo3_runtime.PanicException: assertion failed: dimension::can_index_slice(&v, &dim, &strides).is_ok()
```

It's not super pressing as I have started using the rust crate instead and it works like a charm! Feel free to leave the issue closed, I'll post updates if I have anything helpful.

Thanks for your work!
