### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by clbarnes** [cavemanloverboy/bosque#6]
Would it be possible to get a release of the current master? The tree construction is quite different compared to the last release on crates.io, and I have a dependent crate which I'd like to go up (bosque is one of several optional backends) but can't without a release.

**Comment by cavemanloverboy** [comment]
🫡 on it

**Comment by cavemanloverboy** [comment]
Done. closing issue.

**Comment by clbarnes** [comment]
Much appreciated!
